# Generated by Django 5.1.5 on 2025-02-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_attachment_message_deleted_message_edited_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='attachment',
            field=models.URLField(blank=True, null=True),
        ),
    ]
